name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main
      - chore/reusable-CI
    tags:
      - "*@*"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # 1. Use the Lego Block!
      - name: Setup
        uses: melv1c/github-workflows/.github/actions/setup@main
        with:
          package-manager: bun

      - name: Install dependencies
        uses: melv1c/github-workflows/.github/actions/install-dependencies@main
        with:
          package-manager: bun

      - name: Prisma Validate
        run: bun run prisma:validate

      - name: Prisma Generate
        run: bun run prisma:generate

      - name: Varlock Validate (Development)
        run: bun run env:validate

      - name: Varlock Validate (Staging)
        run: bun run env:validate --filter=frontend --filter=admin
        env:
          APP_ENV: staging

      - name: Varlock Validate (Production)
        run: bun run env:validate --filter=frontend --filter=admin
        env:
          APP_ENV: production

      - name: Varlock Generate
        run: bun run env:generate

      - name: Build
        run: bun run build

      - name: Check
        run: bun run check

  staging-deploy:
    needs:
      - ci
    uses: melv1c/github-workflows/.github/workflows/staging-deploy.yml@main
    with:
      apps: '["frontend", "admin", "backend"]'
      image-name-prefix: fullstack-app
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
