name: Main CI/CD Pipeline

env:
  PACKAGE_MANAGER: bun

on:
  push:
    branches:
      - main
      - chore/reusable-CI
    tags:
      - "*@*"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # 1. Use the Lego Block!
      - name: Setup
        uses: melv1c/github-workflows/.github/actions/setup@main
        with:
          package-manager: ${{ env.PACKAGE_MANAGER }}
